name: CI Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies
      run: pip install -r requirements.txt

    - run: echo "PYTHONPATH перед тестами: $PYTHONPATH"

    - run: export PYTHONPATH=$PYTHONPATH:$(pwd)/src

    - run: pytest tests

    - run: mypy src/

    - run: black --diff --check src/

    - run: isort --check-only --diff src/

    - run: flake8 src/
